---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - BlueMystical
body:
  - type: markdown
    attributes:
      value: |
        The purpose of this template is to create a standardized issue workflow
        for EDHM_UI.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: When I do X, I expect Y to happen.
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actial Behavior
      description: When I do X, Z happens.
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: Steps to Reproduce
      description: What do we have to do to make Z happen.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: false
  - type: dropdown
    id: ed_version
    attributes:
      label: Elite Dangerous Version
      description: What version of Elite Dangerous are you running?
      options:
        - Horizons
        - Odyssey
    validations:
      required: true
  - type: dropdown
    id: ed_source
    attributes:
      label: Elite Dangrous Source
      multiple: false
      options:
        - Frontier
        - Epic Games
        - Steam
  - type: input
    id: edhm_ui_version
    attributes:
      label: EDHM_UI Version
      description: What version of EDHM_UI are you running?
    validations:
      required: true
  - type: input
    id: edhm_version
    attributes:
      label: EDHM Version
      description: |
        What version of EDHM are you using (this should only be
        necessary if you are testing a pre-release)
    validations:
      required: false
  - type: textarea
    id: info
    attributes:
      label: Other Relevant Info
      description: |
        If there is anything else you feel we should know, please
        let us know!
    validations:
      required: false
