---
name: Syntax Checking and Linting
on: # yamllint disable-line rule:truthy
  [pull_request, workflow_dispatch]
  push:
    branches:
      - main
      - 'release/**'
jobs:
  build:
    name: Linting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JSON Lint
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
      - name: Markdown Lint
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: "**.md"
          ignore_files: "CHANGELOG.md"
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v0.0.1
        with:
          file_or_dir: .
